---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-alpine
spec:
  minReadySeconds: 1
  replicas: 5
  template:
    metadata:
      name: jenkins-pod
    spec:
      name: jenkins-pod
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
