---
apiVersion: v1
kind: Service
metadata: 
  name: svc-nginx
  labels:
    app: nginx
spec:
  ports:
    - name: svc-nginx-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP