---
apiVersion: batch/v1
kind: Job
metadata: 
  name: spcjob
spec:
  template:
    metadata:
      name: spc-pod
    spec:
      restartPolicy: OnFailure
      containers:
        - name: spc-cntr
          image: srikanthvelma/spc:v1.0
          ports:
            - containerPort: 8080
          